---
- name: Monday morning review         # metadata
  connection: local                   # no SSH or other connection tech
  hosts: ansibleController            # mapped in hosts
  gather_facts: false                 # no need to grab facts about local controller

  tasks:

    - name: Http lookup to alta3.com
      ansible.builtin.uri:
        url: https://alta3.com
      register: results

    - name: Display results
      ansible.builtin.debug:
        var: results
